<div class="container">
    <div class="row">
        <h1>Return Policy</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.</p>
        
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.</p>
         
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt, sapiente, delectus. Aspernatur enim debitis quam molestiae inventore fugit ipsa dignissimos, hic nesciunt natus minus dicta, modi voluptate provident nihil fugiat.</p>
    </div>
</div>