<div class="container">
    <div class="row">
        <h1>Terms & conditions</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate blanditiis aliquid et atque cumque magnam quos voluptates ducimus dolor, aliquam sunt est, quia iure commodi nemo. Fugiat ut, reprehenderit magnam!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ad eligendi enim cupiditate. Esse molestiae hic, eligendi voluptatem at quibusdam autem nam, quo nostrum voluptate aut sint alias laboriosam provident.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero blanditiis quia id laborum nam quae. Ex, nostrum quaerat, deserunt eaque id facere voluptas nulla facilis eum repellendus fugit animi aut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iure molestiae, velit voluptatibus quasi nostrum ipsum, obcaecati ipsa qui ut voluptates sequi maiores, voluptas quibusdam. Rerum porro repellendus mollitia repellat!</p>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate blanditiis aliquid et atque cumque magnam quos voluptates ducimus dolor, aliquam sunt est, quia iure commodi nemo. Fugiat ut, reprehenderit magnam!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ad eligendi enim cupiditate. Esse molestiae hic, eligendi voluptatem at quibusdam autem nam, quo nostrum voluptate aut sint alias laboriosam provident.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero blanditiis quia id laborum nam quae. Ex, nostrum quaerat, deserunt eaque id facere voluptas nulla facilis eum repellendus fugit animi aut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iure molestiae, velit voluptatibus quasi nostrum ipsum, obcaecati ipsa qui ut voluptates sequi maiores, voluptas quibusdam. Rerum porro repellendus mollitia repellat!</p>
        
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate blanditiis aliquid et atque cumque magnam quos voluptates ducimus dolor, aliquam sunt est, quia iure commodi nemo. Fugiat ut, reprehenderit magnam!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ad eligendi enim cupiditate. Esse molestiae hic, eligendi voluptatem at quibusdam autem nam, quo nostrum voluptate aut sint alias laboriosam provident.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero blanditiis quia id laborum nam quae. Ex, nostrum quaerat, deserunt eaque id facere voluptas nulla facilis eum repellendus fugit animi aut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iure molestiae, velit voluptatibus quasi nostrum ipsum, obcaecati ipsa qui ut voluptates sequi maiores, voluptas quibusdam. Rerum porro repellendus mollitia repellat!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate blanditiis aliquid et atque cumque magnam quos voluptates ducimus dolor, aliquam sunt est, quia iure commodi nemo. Fugiat ut, reprehenderit magnam!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ad eligendi enim cupiditate. Esse molestiae hic, eligendi voluptatem at quibusdam autem nam, quo nostrum voluptate aut sint alias laboriosam provident.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero blanditiis quia id laborum nam quae. Ex, nostrum quaerat, deserunt eaque id facere voluptas nulla facilis eum repellendus fugit animi aut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iure molestiae, velit voluptatibus quasi nostrum ipsum, obcaecati ipsa qui ut voluptates sequi maiores, voluptas quibusdam. Rerum porro repellendus mollitia repellat!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate blanditiis aliquid et atque cumque magnam quos voluptates ducimus dolor, aliquam sunt est, quia iure commodi nemo. Fugiat ut, reprehenderit magnam!Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda ad eligendi enim cupiditate. Esse molestiae hic, eligendi voluptatem at quibusdam autem nam, quo nostrum voluptate aut sint alias laboriosam provident.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero blanditiis quia id laborum nam quae. Ex, nostrum quaerat, deserunt eaque id facere voluptas nulla facilis eum repellendus fugit animi aut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime iure molestiae, velit voluptatibus quasi nostrum ipsum, obcaecati ipsa qui ut voluptates sequi maiores, voluptas quibusdam. Rerum porro repellendus mollitia repellat!</p>
    </div>
</div>